# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\"[\n\x0bRegisterReq\x12\x1a\n\x08username\x18\x01 \x01(\tR\x08username\x12\x1a\n\x08password\x18\x02 \x01(\tR\x08password\x12\x14\n\x05\x65mail\x18\x03 \x01(\tR\x05\x65mail\"*\n\x0cRegisterResp\x12\x1a\n\x08username\x18\x01 \x01(\tR\x08username\"B\n\x08LoginReq\x12\x1a\n\x08username\x18\x01 \x01(\tR\x08username\x12\x1a\n\x08password\x18\x02 \x01(\tR\x08password\"r\n\tLoginResp\x12!\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\tR\x0b\x61\x63\x63\x65ssToken\x12#\n\rrefresh_token\x18\x02 \x01(\tR\x0crefreshToken\x12\x1d\n\nexpires_at\x18\x03 \x01(\x03R\texpiresAt\"6\n\x0fRefreshTokenReq\x12#\n\rrefresh_token\x18\x01 \x01(\tR\x0crefreshToken\"<\n\x07\x43hatReq\x12\x1b\n\tthread_id\x18\x01 \x01(\tR\x08threadId\x12\x14\n\x05query\x18\x02 \x01(\tR\x05query\"&\n\x08\x43hatResp\x12\x1a\n\x08response\x18\x01 \x01(\tR\x08response2\x84\x01\n\x0bUserService\x12\'\n\x08Register\x12\x0c.RegisterReq\x1a\r.RegisterResp\x12\x1e\n\x05Login\x12\t.LoginReq\x1a\n.LoginResp\x12,\n\x0cRefreshToken\x12\x10.RefreshTokenReq\x1a\n.LoginResp2/\n\x0c\x41gentService\x12\x1f\n\x04\x43hat\x12\x08.ChatReq\x1a\t.ChatResp(\x01\x30\x01\x42(Z&github.com/Wh1teCaat/multi-agent/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&github.com/Wh1teCaat/multi-agent/proto'
  _globals['_REGISTERREQ']._serialized_start=15
  _globals['_REGISTERREQ']._serialized_end=106
  _globals['_REGISTERRESP']._serialized_start=108
  _globals['_REGISTERRESP']._serialized_end=150
  _globals['_LOGINREQ']._serialized_start=152
  _globals['_LOGINREQ']._serialized_end=218
  _globals['_LOGINRESP']._serialized_start=220
  _globals['_LOGINRESP']._serialized_end=334
  _globals['_REFRESHTOKENREQ']._serialized_start=336
  _globals['_REFRESHTOKENREQ']._serialized_end=390
  _globals['_CHATREQ']._serialized_start=392
  _globals['_CHATREQ']._serialized_end=452
  _globals['_CHATRESP']._serialized_start=454
  _globals['_CHATRESP']._serialized_end=492
  _globals['_USERSERVICE']._serialized_start=495
  _globals['_USERSERVICE']._serialized_end=627
  _globals['_AGENTSERVICE']._serialized_start=629
  _globals['_AGENTSERVICE']._serialized_end=676
# @@protoc_insertion_point(module_scope)
