"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class RegisterReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERNAME_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    username: builtins.str
    password: builtins.str
    email: builtins.str
    def __init__(
        self,
        *,
        username: builtins.str = ...,
        password: builtins.str = ...,
        email: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["email", b"email", "password", b"password", "username", b"username"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RegisterReq: typing_extensions.TypeAlias = RegisterReq

@typing.final
class RegisterResp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERNAME_FIELD_NUMBER: builtins.int
    username: builtins.str
    def __init__(
        self,
        *,
        username: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["username", b"username"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RegisterResp: typing_extensions.TypeAlias = RegisterResp

@typing.final
class LoginReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERNAME_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    username: builtins.str
    password: builtins.str
    def __init__(
        self,
        *,
        username: builtins.str = ...,
        password: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["password", b"password", "username", b"username"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LoginReq: typing_extensions.TypeAlias = LoginReq

@typing.final
class LoginResp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCESS_TOKEN_FIELD_NUMBER: builtins.int
    REFRESH_TOKEN_FIELD_NUMBER: builtins.int
    EXPIRES_AT_FIELD_NUMBER: builtins.int
    access_token: builtins.str
    """短期 token"""
    refresh_token: builtins.str
    """长期 token"""
    expires_at: builtins.int
    """过期时间"""
    def __init__(
        self,
        *,
        access_token: builtins.str = ...,
        refresh_token: builtins.str = ...,
        expires_at: builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["access_token", b"access_token", "expires_at", b"expires_at", "refresh_token", b"refresh_token"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LoginResp: typing_extensions.TypeAlias = LoginResp

@typing.final
class RefreshTokenReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REFRESH_TOKEN_FIELD_NUMBER: builtins.int
    refresh_token: builtins.str
    def __init__(
        self,
        *,
        refresh_token: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["refresh_token", b"refresh_token"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RefreshTokenReq: typing_extensions.TypeAlias = RefreshTokenReq

@typing.final
class ChatReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    THREAD_ID_FIELD_NUMBER: builtins.int
    QUERY_FIELD_NUMBER: builtins.int
    thread_id: builtins.str
    query: builtins.str
    def __init__(
        self,
        *,
        thread_id: builtins.str = ...,
        query: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["query", b"query", "thread_id", b"thread_id"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ChatReq: typing_extensions.TypeAlias = ChatReq

@typing.final
class ChatResp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESPONSE_FIELD_NUMBER: builtins.int
    response: builtins.str
    def __init__(
        self,
        *,
        response: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["response", b"response"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ChatResp: typing_extensions.TypeAlias = ChatResp
